# Use a base image that has Python installed
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt {ROOT_DIR}

# Install the Python dependencies
RUN {INSTALL_COMMAND}

# Copy the rest of the application code into the container
COPY . .

# Expose the port that Streamlit will run on
EXPOSE {PORT}

# Set the entry point for Streamlit
CMD ["streamlit", "run", "{OUTPUT_DIR}{OUTPUT_FILENAME}", "--server.port={PORT}", "--server.headless=true"]
