# Start with the Python base image for FastAPI
FROM python:3.9-slim as build-stage

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN {installCommand}

# Copy the application files
COPY . .

# Expose the FastAPI server port
EXPOSE 80

# Run FastAPI using Uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
