# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt {ROOT_DIR}

# Install dependencies
RUN {INSTALL_COMMAND}

# Copy the rest of the application code
COPY . .

# Expose the port FastAPI runs on
EXPOSE {PORT}

# Command to run FastAPI with Uvicorn
CMD ["uvicorn", "{OUTPUT_FILENAME}:app", "--host", "0.0.0.0", "--port", "{PORT}"]
