# Start from an appropriate base image
FROM node:22-alpine AS build

# Set the working directory for building
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN {INSTALL_COMMAND}

# Copy all source code
COPY . .
{BUILD_COMMAND}
# Build Stage 2

FROM build AS production-stage
WORKDIR /app

# Only `.output` folder is needed from the build stage
COPY --from=build /app/.output/ ./

# Change the port and host
ENV PORT {PORT}
ENV HOST 0.0.0.0

EXPOSE {PORT}

CMD ["node", "{OUTPUT_DIRECTORY}{OUTPUT_FILENAME}"]
