# Start from an appropriate base image
FROM node:22-slim as build-stage

# Set the working directory for building
WORKDIR /app

# Install dependencies
COPY package.json {rootDir}
RUN {installCommand}

# Copy all source code
COPY . .

# Build the project
RUN {buildCommand}

# Define environment variables
ENV NODE_ENV=production
ENV NITRO_PORT={PORT}

# Expose the port the application will run on
EXPOSE {PORT}

# Start the application
CMD [ "npm", "run", "start" ]
