# Start from an appropriate base image
FROM node:22-slim as base

# Set the working directory for building
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* {ROOT_DIR}
RUN {INSTALL_COMMAND}

# Copy all source code
COPY . .
{BUILD_COMMAND}

# Define environment variables
ENV NODE_ENV=production
ENV NITRO_PORT={PORT}
ENV HOST=0.0.0.0

# Expose the port the application will run on
EXPOSE {PORT}

# Start the application
CMD ["node", "{OUTPUT_FILENAME}"]
