stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: auto-cicd
  CONTAINER_IMAGE_NAME: auto-cicd
  CONTAINER_IMAGE: ${AWS_ECR_URL}/${CONTAINER_IMAGE_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_NAMESPACE: self-service-suite

# Build the Docker container image
build-job:
  stage: build
  tags:
    # optional: Docker is the default runner
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    # Create repository if needed
    - >
      aws ecr create-repository --repository-name ${CONTAINER_IMAGE_NAME}
      || echo "Repository might have already existed"
  script:
    # Build the container image
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    # Push container images to registry
    - docker push ${CONTAINER_IMAGE_TAGGED}

# Deploy to Kubernetes
deploy-job:
  stage: deploy
  tags:
    # optional: Docker is the default runner
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - kubectl config use-context eks-internal-public/gitlab-agent-for-kubernetes:eks-internal-public
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    # Apply the Config
    - kubectl apply -f config_configmap.yml
    # Apply the Deployment
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    # Wait for rollout to complete
    - kubectl rollout status deployment/${APPLICATION_NAME} --timeout=5m