/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    DeployBuildSettings: typeof import('./src/components/deploy/DeployBuildSettings.vue')['default']
    DeployButton: typeof import('./src/components/deploy/DeployButton.vue')['default']
    DeployConfirmDialog: typeof import('./src/components/deploy/DeployConfirmDialog.vue')['default']
    DeployDialog: typeof import('./src/components/deploy/DeployDialog.vue')['default']
    DeployEnvironmentSettings: typeof import('./src/components/deploy/DeployEnvironmentSettings.vue')['default']
    DeployEnvStatus: typeof import('./src/components/deploy/DeployEnvStatus.vue')['default']
    DeployFrameworkSelector: typeof import('./src/components/deploy/DeployFrameworkSelector.vue')['default']
    DeployHandler: typeof import('./src/components/deploy/DeployHandler.vue')['default']
    DeployNextStepsDialog: typeof import('./src/components/deploy/DeployNextStepsDialog.vue')['default']
    MoreInformation: typeof import('./src/components/MoreInformation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toaster: typeof import('./src/components/Toaster.vue')['default']
  }
}
