packageManagers:
  npm:
    name: npm
    commands:
      install: npm install
      build: npm run build
    detectionFiles:
      - file: package-lock.json
    languages:
      - javascript
      - typescript
  yarn:
    name: yarn
    commands:
      install: yarn install
      build: yarn build
    detectionFiles:
      - file: yarn.lock
    languages:
      - javascript
      - typescript
  pnpm:
    name: pnpm
    commands:
      install: corepack enable pnpm && pnpm i
      build: corepack enable pnpm && pnpm run build
    detectionFiles:
      - file: pnpm-lock.yaml
    languages:
      - javascript
      - typescript
  pip:
    name: pip
    commands:
      install: pip install --no-cache-dir -r requirements.txt
    detectionFiles:
      - file: requirements.txt
    languages:
      - python
frameworks:
  express:
    name: Express
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg'
    languages:
      - javascript
      - typescript
    userConfigurable:
      buildCommand:
        defaultEmpty: true
      installCommand:
        defaultEmpty: false
      outputFile:
        defaultEmpty: false
      port:
        defaultEmpty: false
    outputFile: app.js
    port: 3000
    files: 
      - kubernetes_manifest.yml
      - Dockerfile
      - .gitlab-ci.yml
    configFiles:
      - file:
          - package.json
        checkFor:
          - express
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - package.json
  fastapi:
    name: FastAPI
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fastapi/fastapi-original.svg'
    languages:
      - python
    userConfigurable:
      installCommand:
        defaultEmpty: false
      outputFile:
        defaultEmpty: false
      port:
        defaultEmpty: false
    outputFile: main.py
    port: 8000
    files: 
      - kubernetes_manifest.yml
      - Dockerfile
      - .gitlab-ci.yml
    configFiles:
      - file:
          - requirements.txt
        checkFor:
          - fastapi
    supportedManagers:
      - manager: pip
        requiredFiles:
          - requirements.txt
    defaultManager: pip
  nextjs:
    name: NextJs
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg'
    languages:
      - tsx
      - jsx
      - typescript
      - javascript
    userConfigurable:
      buildCommand:
        defaultEmpty: false
      installCommand:
        defaultEmpty: false
    outputFile: .next/server.js
    port: 3000
    files: 
      - kubernetes_manifest.yml
      - Dockerfile
      - .gitlab-ci.yml
    configFiles:
      - file:
          - next.config.ts
          - next.config.mts
          - next.config.js
          - next.config.mjs
        checkFor:
          - NextConfig
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - - next.config.ts
        - next.config.mts
        - next.config.js
        - next.config.mjs
      - package.json
    tips:
      - text: >-
          To deploy you need to add the config "output: 'standalone'" in your
          next.config.js
        link: >-
          https://nextjs.org/docs/pages/api-reference/config/next-config-js/output#automatically-copying-traced-files
  nuxt:
    name: Nuxt
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nuxt/nuxt-original.svg'
    languages:
      - vue
      - typescript
      - javascript
    userConfigurable:
      buildCommand:
        defaultEmpty: false
      installCommand:
        defaultEmpty: false
    outputFile: /app/server/index.mjs
    port: 3000
    files: 
      - kubernetes_manifest.yml
      - Dockerfile
      - .gitlab-ci.yml
    configFiles:
      - file:
          - nuxt.config.ts
          - nuxt.config.mts
          - nuxt.config.js
          - nuxt.config.mjs
        checkFor:
          - defineNuxtConfig
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - - nuxt.config.ts
        - nuxt.config.mts
        - nuxt.config.js
        - nuxt.config.mjs
      - package.json
  streamlit:
    name: Streamlit
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/streamlit/streamlit-original.svg'
    languages:
      - python
    userConfigurable:
      installCommand:
        defaultEmpty: false
      outputFile:
        defaultEmpty: false
      port:
        defaultEmpty: false
    outputFile: app.py
    port: 8501
    files: 
      - kubernetes_manifest.yml
      - Dockerfile
      - .gitlab-ci.yml
    configFiles:
      - file:
          - requirements.txt
        checkFor:
          - streamlit
    supportedManagers:
      - manager: pip
        requiredFiles:
          - requirements.txt
    defaultManager: pip
  vite:
    name: Vite
    image: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg'
    languages:
      - vue
      - typescript
      - javascript
      - tsx
      - jsx
    userConfigurable:
      buildCommand:
        defaultEmpty: false
      installCommand:
        defaultEmpty: false
    outputFile: dist/index.html
    port: 5173
    files:
      - kubernetes_manifest.yml
      - Dockerfile
      - .gitlab-ci.yml
      - nginx.conf
    configFiles:
      - file:
          - vite.config.ts
          - vite.config.mts
          - vite.config.js
          - vite.config.mjs
        checkFor:
          - defineConfig
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - - vite.config.ts
        - vite.config.mts
        - vite.config.js
        - vite.config.mjs
      - package.json
usefulLinks:
  - name: K8s Dashboard
    icon: 'http://172.16.98.151:31030/icon.png'
    url: 'http://172.16.98.151:31389/?namespace=auto-cicd'
    description:
      en: >-
        Access the Kubernetes Dashboard to monitor, manage, and undeploy your
        running applications.
      ja: Kubernetes ダッシュボードにアクセスして、実行中のアプリケーションの監視・管理やデプロイ解除を行うことができます。
