# AUTO CICD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: auto-cicd-env
          volumeMounts:
            - name: auto-cicd-config
              mountPath: /app/config.yml
              subPath: config.yml
            - name: auto-cicd-config
              mountPath: /app/templates/common/.gitlab-ci.yml
              subPath: .gitlab-ci.yml
            - name: auto-cicd-config
              mountPath: /app/templates/common/kubernetes_manifest.yml
              subPath: kubernetes_manifest.yml

      volumes:
        - name: auto-cicd-config
          configMap:
            name: auto-cicd

      imagePullSecrets:
        - name: ecr-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${APPLICATION_NAME}
  ports:
    - port: 80

---
# ISSUE CREATOR
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-cicd-issue-creator
  labels:
    app.kubernetes.io/name: auto-cicd-issue-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auto-cicd-issue-creator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auto-cicd-issue-creator
    spec:
      containers:
        - name: auto-cicd-issue-creator
          image: "${AWS_ECR_URL}/issue-creator:v1.0.8"
          envFrom:
            - secretRef:
                name: auto-cicd-env
                optional: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "600m"
      imagePullSecrets:
        - name: ecr-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: auto-cicd-issue-creator
  labels:
    app.kubernetes.io/name: auto-cicd-issue-creator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auto-cicd-issue-creator
  ports:
    - port: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Self-Service Suite
    gethomepage.dev/name: Auto-CICD
    gethomepage.dev/description: CICD configuration generator
    gethomepage.dev/icon: https://gitlab.jtektrnd.net/uploads/-/system/project/avatar/2866/auto-cicd.png

    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - ${APPLICATION_NAME}.higashikariya.jtektrnd.net
      secretName: ${APPLICATION_NAME}-tls
  rules:
    - host: ${APPLICATION_NAME}.higashikariya.jtektrnd.net
      http:
        paths:
          - path: /issue-creator
            pathType: Prefix
            backend:
              service:
                name: auto-cicd-issue-creator
                port:
                  number: 3000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${APPLICATION_NAME}
                port:
                  number: 80
