apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 80
          env:
            - name: VITE_APP_GITLAB_URL
              value: http://10.115.1.14

            - name: VITE_APP_GITLAB_OAUTH_ID
              value: cc0f76a696f2d509832145636d714d66095b82b47981975b25501e7739d4e255

            - name: VITE_APP_GITLAB_OAUTH_STATE_VALIDATOR
              value: auto-cicd-state

            - name: VITE_APP_DEPLOYED_NAMESPACE
              value: auto-cicd

            - name: VITE_APP_IMAGE_PULL_SECRET_NAME
              value: ecr-credentials

            - name: VITE_APP_GITLAB_GROUP_MANAGER_URL
              value: http://172.16.98.151:30173
            
            - name: VITE_APP_SUPPORT_CONTACTS
              value: mdi-gitlab|GitLab Issues|http://10.115.1.14/on-premise-k8s-cluster/fabel/auto-cicd/-/issues
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - port: 80
      nodePort: ${K8S_NODEPORT}
