FROM python:3.11.6-slim

ENV POETRY_VERSION=1.8.3 \
    POETRY_HOME=/opt/poetry \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/opt/.cache

ENV VIRTUAL_ENV=/code/.venv \
    PATH="/code/.venv/bin:$PATH"

WORKDIR /code

RUN python3 -m venv $POETRY_HOME \
    && $POETRY_HOME/bin/pip install -U pip setuptools \
    && $POETRY_HOME/bin/pip install poetry==${POETRY_VERSION}

ENV PATH="${PATH}:${POETRY_HOME}/bin"

# COPY ./pyproject.toml ./pyproject.toml
COPY . .

RUN poetry install && rm -rf $POETRY_CACHE_DIR






EXPOSE 80
CMD [ "python", "-m", "streamlit", "run", "app.py", "--server.port=80", "--server.address=0.0.0.0"]
