stages:
  - validate
  - build
  - deploy

# Needed to use Docker command in CICD
image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:24.0.7-dind

variables:
  APPLICATION_NAME: { APPLICATION_NAME }
  CONTAINER_IMAGE_NAME: { APPLICATION_NAME }
  CONTAINER_IMAGE: ${AWS_ECR_URL}/${CONTAINER_IMAGE_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_NAMESPACE: auto-cicd
  K8S_ECR_SECRET_NAME: ecr-credentials
  PORT: 80

# Validate the environment variables
validate-job:
  stage: validate
  script:
    - |
      echo "Validating environment variables..."
      if [ -z "$APPLICATION_NAME" ]; then
        echo "ERROR: APPLICATION_NAME is not set!"
        exit 1
      fi
      if [ -z "$K8S_NAMESPACE" ]; then
        echo "ERROR: K8S_NAMESPACE is not set!"
        exit 1
      fi
      if [ -z "$AWS_ECR_URL" ]; then
        echo "ERROR: AWS_ECR_URL is not set!"
        exit 1
      fi
      if [ -z "$AWS_SES_PORT" ]; then
        echo "ERROR: AWS_SES_PORT is not set!"
        exit 1
      fi
      if [ -z "$AWS_SES_HOST" ]; then
        echo "ERROR: AWS_SES_HOST is not set!"
        exit 1
      fi
      if [ -z "$AWS_SES_USERNAME" ]; then
        echo "ERROR: AWS_SES_USERNAME is not set!"
        exit 1
      fi
      if [ -z "$AWS_SES_PASSWORD" ]; then
        echo "ERROR: AWS_SES_PASSWORD is not set!"
        exit 1
      fi
      if [ -z "$AWS_SES_FROM" ]; then
        echo "ERROR: AWS_SES_FROM is not set!"
        exit 1
      fi
      if [ -z "$GITLAB_USER_EMAIL" ]; then
        echo "ERROR: GITLAB_USER_EMAIL is not set!"
        exit 1
      fi
      echo "All environment variables are set correctly."

# Build the Docker container image
build-job:
  stage: build
  only:
    - master
    - main
  before_script:
    # Create repository if needed
    - >
      aws ecr create-repository --repository-name ${CONTAINER_IMAGE_NAME}
      || echo "Repository might have already existed"
    # Log in to the registry (AWS credentials are stored as GitLab env variables)
    - >
      aws ecr get-login-password
      | docker login
      --username AWS
      --password-stdin
      ${AWS_ECR_URL}
  script:
    # Build the container image
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    # Push container images to registry
    - docker push ${CONTAINER_IMAGE_TAGGED}

# Deploy to Kubernetes
deploy-job:
  stage: deploy
  tags:
    - dind
  only:
    - master
    - main
  before_script:
    # Create Kubernetes secret for accessing ECR
    - >
      kubectl create secret docker-registry ${K8S_ECR_SECRET_NAME}
      --docker-server=${AWS_ECR_URL}
      --docker-username=AWS
      --docker-password $(aws ecr get-login-password)
      --dry-run=client -o yaml
      | kubectl apply -f -
  script:
    # Deploy the app to Kubernetes using the Kubernetes manifest
    - KUBECTL_APPLY_OUTPUT=$(envsubst < kubernetes_manifest.yml | kubectl apply -f -)

    - KUBECTL_GET_SVC=$(kubectl get svc $APPLICATION_NAME | grep $APPLICATION_NAME)

    - |
      if [[ -z "$KUBECTL_GET_SVC" ]]; then
        echo "Error: Could not find service port for $APPLICATION_NAME"
        exit 1
      fi

    - PORT=$(sed 's/.*80:\(.*\)\/TCP.*/\1/' <<< "$KUBECTL_GET_SVC")

    - echo "The APP is available at http://172.16.98.151:$PORT"

    - |
      if [[ $KUBECTL_APPLY_OUTPUT == *"created"* ]]; then
        echo "Deployment was newly created, Notifying user by email"

        docker run \
          -e SMTP_PORT=$AWS_SES_PORT \
          -e SMTP_HOST=$AWS_SES_HOST \
          -e SMTP_USERNAME=$AWS_SES_USERNAME \
          -e SMTP_PASSWORD=$AWS_SES_PASSWORD \
          -e SMTP_TO=$GITLAB_USER_EMAIL \
          -e SMTP_FROM=$AWS_SES_FROM \
          -e SMTP_SUBJECT="Auto CICD" \
          -e SMTP_MESSAGE="Your application $APPLICATION_NAME is being deployed to http://172.16.98.151:$PORT. Please note that it might take a few minutes for the application to start." \
          moreillon/sendemail
      else
        echo "Deployment was just updated, no need to notify user"
      fi

  environment:
    name: production
    kubernetes:
      namespace: ${K8S_NAMESPACE}
