packageManagers:
  npm:
    name: npm
    commands:
      install: npm install
      build: npm run build
    detectionFiles:
      - file: package-lock.json
    languages:
      - javascript
      - typescript
  yarn:
    name: yarn
    commands:
      install: yarn install
      build: yarn build
    detectionFiles:
      - file: yarn.lock
    languages:
      - javascript
      - typescript
  pnpm:
    name: pnpm
    commands:
      install: corepack enable pnpm && pnpm i
      build: corepack enable pnpm && pnpm run build
    detectionFiles:
      - file: pnpm-lock.yaml
    languages:
      - javascript
      - typescript
  pip:
    name: pip
    commands:
      install: pip install --no-cache-dir -r requirements.txt
    detectionFiles:
      - file: requirements.txt
    languages:
      - python
frameworks:
  express:
    name: Express
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg"
    languages:
      - javascript
      - typescript
    userConfigurable:
      buildCommand:
        defaultEmpty: true
      installCommand:
        defaultEmpty: false
      outputFile:
        defaultEmpty: false
      port:
        defaultEmpty: false
    outputFile: app.js
    port: 3000
    files:
      - /templates/express/Dockerfile
    configFiles:
      - file:
          - package.json
        checkFor:
          - express
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - package.json
  fastapi:
    name: FastAPI
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fastapi/fastapi-original.svg"
    languages:
      - python
    userConfigurable:
      installCommand:
        defaultEmpty: false
      outputFile:
        defaultEmpty: false
      port:
        defaultEmpty: false
    outputFile: main.py
    port: 8000
    files:
      - /templates/fastapi/Dockerfile
    configFiles:
      - file:
          - requirements.txt
        checkFor:
          - fastapi
    supportedManagers:
      - manager: pip
        requiredFiles:
          - requirements.txt
    defaultManager: pip
  nextjs:
    name: NextJs
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg"
    languages:
      - tsx
      - jsx
      - typescript
      - javascript
    userConfigurable:
      buildCommand:
        defaultEmpty: false
      installCommand:
        defaultEmpty: false
    outputFile: .next/server.js
    port: 3000
    files:
      - /templates/nextjs/Dockerfile
    configFiles:
      - file:
          - next.config.ts
          - next.config.mts
          - next.config.js
          - next.config.mjs
        checkFor:
          - NextConfig
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - - next.config.ts
        - next.config.mts
        - next.config.js
        - next.config.mjs
      - package.json
    tips:
      - text: >-
          To deploy you need to add the config "output: 'standalone'" in your
          next.config.js
        link: >-
          https://nextjs.org/docs/pages/api-reference/config/next-config-js/output#automatically-copying-traced-files
  nuxt:
    name: Nuxt
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nuxt/nuxt-original.svg"
    languages:
      - vue
      - typescript
      - javascript
    userConfigurable:
      buildCommand:
        defaultEmpty: false
      installCommand:
        defaultEmpty: false
    outputFile: /app/server/index.mjs
    port: 3000
    files:
      - /templates/nuxt/Dockerfile
    configFiles:
      - file:
          - nuxt.config.ts
          - nuxt.config.mts
          - nuxt.config.js
          - nuxt.config.mjs
        checkFor:
          - defineNuxtConfig
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - - nuxt.config.ts
        - nuxt.config.mts
        - nuxt.config.js
        - nuxt.config.mjs
      - package.json
  streamlit:
    name: Streamlit
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/streamlit/streamlit-original.svg"
    languages:
      - python
    userConfigurable:
      installCommand:
        defaultEmpty: false
      outputFile:
        defaultEmpty: false
      port:
        defaultEmpty: false
    outputFile: app.py
    port: 8501
    files:
      - /templates/streamlit/Dockerfile
    configFiles:
      - file:
          - requirements.txt
        checkFor:
          - streamlit
    supportedManagers:
      - manager: pip
        requiredFiles:
          - requirements.txt
    defaultManager: pip
  vite:
    name: Vite
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg"
    languages:
      - vue
      - typescript
      - javascript
      - tsx
      - jsx
    userConfigurable:
      buildCommand:
        defaultEmpty: false
      installCommand:
        defaultEmpty: false
    outputFile: dist/index.html
    port: 5173
    files:
      - /templates/vite/Dockerfile
      - /templates/vite/nginx.conf
    configFiles:
      - file:
          - vite.config.ts
          - vite.config.mts
          - vite.config.js
          - vite.config.mjs
        checkFor:
          - defineConfig
    supportedManagers:
      - manager: npm
        requiredFiles:
          - package-lock.json
      - manager: yarn
        requiredFiles:
          - yarn.lock
      - manager: pnpm
        requiredFiles:
          - pnpm-lock.yaml
    defaultManager: npm
    requiredFiles:
      - - vite.config.ts
        - vite.config.mts
        - vite.config.js
        - vite.config.mjs
      - package.json
usefulLinks:
  - name: Deployment Manager
    icon: "https://gitlab.jtektrnd.net/uploads/-/system/project/avatar/4058/apps-box.png"
    url: "https://deployment-manager.higashikariya.jtektrnd.net"
    description:
      en: >-
        Access the Deployment Manager to monitor, manage, and undeploy your
        running applications.
      ja: Deployment Manager にアクセスして、実行中のアプリケーションの監視・管理やデプロイ解除を行うことができます。

  - name: Apache Answer
    icon: "https://answer.jtektrnd.net/favicon.ico"
    url: "https://answer.jtektrnd.net/"
    description:
      en: >-
        Access the Apache Answer knowledge base and community Q&A platform.
      ja: >-
        Apache Answer のナレッジベースおよび Q&A プラットフォームに
        アクセスできます。

  - name: Feedback
    icon: "mdi-message-alert-outline"
    url: "https://gitlab.jtektrnd.net/on-premise-k8s-cluster/fabel/auto-cicd/-/work_items/new?type=Issue&initialCreationContext=list-route"
    description:
      en: >-
        Submit feedback, improvement requests, or report issues regarding the
        platform and applications.
      ja: >-
        プラットフォームやアプリケーションに関するフィードバック、
        改善要望、不具合報告を送信できます。

  - name: Contact Support
    icon: "mdi-email-outline"
    url: "mailto:kevin_fabel@jtekt.co.jp?subject=Auto%20CI%2FCD"
    description:
      en: >-
        Contact the support team by email for assistance or inquiries.
      ja: >-
        サポートやお問い合わせについて、メールでサポートチームへ
        連絡できます。
footerMessage:
  en: "You can create your own group in <a href='https://gitlab-subgroup-creator.higashikariya.jtektrnd.net/' target='_blank'>GitLab Subgroup Creator</a>"
  ja: "<a href='https://gitlab-subgroup-creator.higashikariya.jtektrnd.net/' target='_blank'>GitLab Subgroup Creator</a> で独自のグループを作成できます"
