# Start from an appropriate base image
FROM node:22-alpine as base

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* {ROOT_DIR}
RUN {INSTALL_COMMAND}

# Copy all source code
COPY . .
{BUILD_COMMAND}
# Deploy the app
FROM nginx:stable-alpine as production-stage

# Set working directory for nginx
WORKDIR /usr/share/nginx/

# Clean the default html folder and create a new one
RUN rm -rf html && mkdir html

# Copy nginx configuration and built application files
COPY {ROOT_DIR}nginx.conf /etc/nginx/
COPY --from=base /app/{OUTPUT_DIR} /usr/share/nginx/html

# Run the server in the foreground
CMD ["nginx", "-g", "daemon off;"]
