# Start from an appropriate base image
FROM node:22-alpine as base

# Set the working directory for building
WORKDIR /app

# Install dependencies
COPY package.json {ROOT_DIR}
RUN {INSTALL_COMMAND}

# Copy all source code
COPY . .

# Build the project
RUN {BUILD_COMMAND}

# Deploy the app
FROM nginx:stable-alpine as production-stage

# Set working directory for nginx
WORKDIR /usr/share/nginx/

# Clean the default html folder and create a new one
RUN rm -rf html && mkdir html

# Copy nginx configuration and built application files
COPY ./nginx.conf /etc/nginx/
COPY --from=build-stage /app/{OUTPUT_DIR} /usr/share/nginx/html

# Run the server in the foreground
CMD ["nginx", "-g", "daemon off;"]
