# Start from an appropriate base image
FROM node:22-alpine as base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* {ROOT_DIR}
RUN {INSTALL_COMMAND}

# Copy all source code
COPY . .
{BUILD_COMMAND}
# Deploy the app
FROM nginx:stable-alpine as production-stage

# Set working directory for nginx
WORKDIR /usr/share/nginx/

# Clean the default html folder and create a new one
RUN rm -rf html && mkdir html

# Copy nginx configuration and built application files
COPY {ROOT_DIR}nginx.conf /etc/nginx/
COPY --from=build-stage /app/{OUTPUT_DIR} /usr/share/nginx/html

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 vite

USER vite

# Run the server in the foreground
CMD ["nginx", "-g", "daemon off;"]
